name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  cov:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: "0"
      RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    steps:
    - uses: actions/checkout@v2
    - name: install tarpaulin
      run: wget "https://github.com/xd009642/tarpaulin/releases/download/0.18.0-alpha2/cargo-tarpaulin-0.18.0-alpha2-travis.tar.gz" && sudo tar -xf cargo-tarpaulin*.tar.gz
    - name: run tarpaulin
      run: ./cargo-tarpaulin -o Lcov
    - uses: coverallsapp/github-action@master
      with:
        flag-name: "Unit"
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Formatting
      run: cargo fmt -- --check
